layout_spectrum: 1
color:
  saturation: 0.07394695
  lightness: 0.08255692
  brandStrength: 0.4848229
  brandColors:
    - '#151F20'
    - '#CE9A42'
    - '#91310D'
    - '#E1D1BD'
    - '#6D8877'
  rhythmicContrast: 0.9461148
typography_spectrum: 0
name: Digital Marketing Cringe
